//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public short MaterialsID { get; set; }
        public string NameMaterial { get; set; }
        public Nullable<short> TypeMaterialID { get; set; }
        public Nullable<short> DepartamentID { get; set; }
        public Nullable<short> StellazhID { get; set; }
        public Nullable<short> ShelfID { get; set; }
        public Nullable<short> purposeID { get; set; }
    
        public virtual Departament Departament { get; set; }
        public virtual purpose purpose { get; set; }
        public virtual Shelf Shelf { get; set; }
        public virtual Stellazh Stellazh { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
