//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public short OrdersID { get; set; }
        public Nullable<short> TypeOrdersID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public Nullable<short> MaterialId { get; set; }
        public Nullable<short> WhoCreateOrder { get; set; }
        public string Info { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual TypeOrders TypeOrders { get; set; }
        public virtual Users Users { get; set; }
    }
}
